name: Build and Release

on:
  push:
    tags:
      - 'v0.*'

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up repository
        uses: actions/checkout@master

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: jdk+fx

      - name: Run Clean Checks
        run: ./gradlew clean check

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up repository
        uses: actions/checkout@master

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: jdk+fx

      - name: Build Jar
        run: ./gradlew clean shadowJar

      - name: Create Release
        id: create_release
#        uses: actions/create-release@v1
        uses: softprops/action-gh-release@v1
        with:
          body_path: ./RELEASE.md
          draft: false
          prerelease: true
          files: build/libs/duke.jar
          name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          fail_on_unmatched_files: true
          token: ${{ secrets.GITHUB_TOKEN }}